"""initial schema

Revision ID: bb602a415b1a
Revises: 
Create Date: 2026-04-15 22:44:03.716645+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb602a415b1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('rows_count', sa.Integer(), nullable=True),
    sa.Column('columns_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_profiles_file_id'), ['file_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolution_agent_feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('agent_output', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolution_agent_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolution_agent_feedback_session_id'), ['session_id'], unique=False)

    op.create_table('evolution_execution_patterns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pattern_type', sa.String(length=32), nullable=False),
    sa.Column('intent_hash', sa.String(length=64), nullable=False),
    sa.Column('intent_summary', sa.Text(), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('avg_duration_ms', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolution_execution_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolution_execution_patterns_intent_hash'), ['intent_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_execution_patterns_pattern_type'), ['pattern_type'], unique=False)

    op.create_table('evolution_improvement_proposals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('improvement_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('proposed_change', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolution_improvement_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolution_improvement_proposals_status'), ['status'], unique=False)

    op.create_table('evolution_system_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cycle_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolution_system_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolution_system_log_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('semantic_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uasr_batch_embeddings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('batch_id', sa.String(length=128), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uasr_batch_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uasr_batch_embeddings_source_id'), ['source_id'], unique=False)

    op.create_table('uasr_distribution_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('histogram', sa.JSON(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('null_rate', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uasr_distribution_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uasr_distribution_snapshots_source_id'), ['source_id'], unique=False)

    op.create_table('uasr_drift_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('drift_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('kl_divergence', sa.Float(), nullable=True),
    sa.Column('cosine_distance', sa.Float(), nullable=True),
    sa.Column('drift_vector', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uasr_drift_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uasr_drift_events_source_id'), ['source_id'], unique=False)

    op.create_table('uasr_healing_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_drift_events', sa.Integer(), nullable=False),
    sa.Column('resolved_anomalies', sa.Integer(), nullable=False),
    sa.Column('avg_latency_seconds', sa.Float(), nullable=False),
    sa.Column('recovery_rate', sa.Float(), nullable=False),
    sa.Column('hu_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uasr_healing_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uasr_healing_metrics_domain'), ['domain'], unique=False)

    op.create_table('uasr_recovery_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('drift_event_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('shim_code', sa.Text(), nullable=True),
    sa.Column('shim_language', sa.String(length=16), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('post_kl_divergence', sa.Float(), nullable=True),
    sa.Column('latency_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uasr_recovery_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uasr_recovery_records_drift_event_id'), ['drift_event_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aggregation', sa.String(length=32), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['semantic_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semantic_fields')
    op.drop_table('document_embeddings')
    op.drop_table('users')
    with op.batch_alter_table('uasr_recovery_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uasr_recovery_records_drift_event_id'))

    op.drop_table('uasr_recovery_records')
    with op.batch_alter_table('uasr_healing_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uasr_healing_metrics_domain'))

    op.drop_table('uasr_healing_metrics')
    with op.batch_alter_table('uasr_drift_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uasr_drift_events_source_id'))

    op.drop_table('uasr_drift_events')
    with op.batch_alter_table('uasr_distribution_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uasr_distribution_snapshots_source_id'))

    op.drop_table('uasr_distribution_snapshots')
    with op.batch_alter_table('uasr_batch_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uasr_batch_embeddings_source_id'))

    op.drop_table('uasr_batch_embeddings')
    op.drop_table('semantic_models')
    with op.batch_alter_table('evolution_system_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_system_log_cycle_id'))

    op.drop_table('evolution_system_log')
    with op.batch_alter_table('evolution_improvement_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_improvement_proposals_status'))

    op.drop_table('evolution_improvement_proposals')
    with op.batch_alter_table('evolution_execution_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_execution_patterns_pattern_type'))
        batch_op.drop_index(batch_op.f('ix_evolution_execution_patterns_intent_hash'))

    op.drop_table('evolution_execution_patterns')
    with op.batch_alter_table('evolution_agent_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_agent_feedback_session_id'))

    op.drop_table('evolution_agent_feedback')
    op.drop_table('documents')
    with op.batch_alter_table('dataset_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_profiles_file_id'))

    op.drop_table('dataset_profiles')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
