"""gateway persistence and audit ledger baseline

Revision ID: 5e19034a50f4
Revises: f4a5b6c7d8e9
Create Date: 2026-07-24 12:17:46.854756+00:00

Brings ``api_gateway/persistence.py`` (8 tables) and
``shared/audit_ledger.py`` (1 table) under Alembic. Both modules previously
relied solely on ``Base.metadata.create_all`` at process startup, so a prod
DB could never be ALTERed via migration — this is the initial baseline so
future schema changes to either module get a real migration. DDL below is
autogenerated from the CURRENT model definitions (see ``alembic/env.py``,
which now registers both Bases' metadata alongside metadata_store's), so it
matches column types / nullability / defaults / constraints exactly.

Idempotent by design: many existing deployments already have these tables
from ``create_all`` (which predates this migration and is left in place as
a dev/test fallback — see the module docstrings). Each ``create_table`` is
guarded by an existence check so running this against such a DB is a
no-op for tables already present, while a genuinely fresh DB gets the full
schema. ``create_all`` and this migration build identical DDL from the same
SQLAlchemy Table objects, so a pre-existing table is trusted as already
matching the current model — nothing further to reconcile.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e19034a50f4'
down_revision: Union[str, None] = 'f4a5b6c7d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names())

    # ### commands auto generated by Alembic (from api_gateway.persistence /
    # shared.audit_ledger model metadata), then wrapped per-table with an
    # existence check — see module docstring. ###
    if 'gateway_chat_messages' not in existing_tables:
        op.create_table('gateway_chat_messages',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('workspace_id', sa.String(length=64), nullable=False),
        sa.Column('session_id', sa.String(length=128), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.String(length=64), nullable=False),
        sa.Column('created_ts', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('gateway_chat_messages', schema=None) as batch_op:
            batch_op.create_index('ix_chat_ws_session_created', ['workspace_id', 'session_id', 'created_ts'], unique=False)
            batch_op.create_index(batch_op.f('ix_gateway_chat_messages_workspace_id'), ['workspace_id'], unique=False)

    if 'gateway_file_metadata' not in existing_tables:
        op.create_table('gateway_file_metadata',
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_suffix', sa.String(length=16), nullable=False),
        sa.Column('row_count', sa.Integer(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('mtime', sa.Float(), nullable=False),
        sa.Column('last_indexed_at', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('file_path')
        )
        with op.batch_alter_table('gateway_file_metadata', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_file_metadata_mtime'), ['mtime'], unique=False)

    if 'gateway_pipelines' not in existing_tables:
        op.create_table('gateway_pipelines',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('workspace_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('definition_json', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('source_label', sa.String(length=255), nullable=False),
        sa.Column('sink_type', sa.String(length=64), nullable=False),
        sa.Column('step_count', sa.Integer(), nullable=False),
        sa.Column('tags_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.String(length=64), nullable=False),
        sa.Column('updated_at', sa.String(length=64), nullable=False),
        sa.Column('created_ts', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('gateway_pipelines', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_pipelines_workspace_id'), ['workspace_id'], unique=False)
            batch_op.create_index('ix_pipelines_ws_created', ['workspace_id', sa.literal_column('created_ts DESC')], unique=False)

    if 'gateway_query_history' not in existing_tables:
        op.create_table('gateway_query_history',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('sql', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('rows', sa.Integer(), nullable=False),
        sa.Column('execution_time', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.String(length=64), nullable=False),
        sa.Column('created_ts', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('gateway_query_history', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_query_history_created_ts'), ['created_ts'], unique=False)
            batch_op.create_index('ix_query_history_created_ts_desc', [sa.literal_column('created_ts DESC')], unique=False)

    if 'gateway_saved_queries' not in existing_tables:
        op.create_table('gateway_saved_queries',
        sa.Column('id', sa.String(length=64), nullable=False),
        sa.Column('workspace_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('sql', sa.Text(), nullable=False),
        sa.Column('prompt', sa.Text(), nullable=True),
        sa.Column('starred', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.String(length=64), nullable=False),
        sa.Column('created_ts', sa.Float(), nullable=False),
        sa.Column('updated_at', sa.String(length=64), nullable=False),
        sa.Column('schedule_json', sa.Text(), nullable=True),
        sa.Column('next_run_at', sa.String(length=64), nullable=True),
        sa.Column('last_run_at', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('gateway_saved_queries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_saved_queries_workspace_id'), ['workspace_id'], unique=False)
            batch_op.create_index('ix_saved_queries_ws_starred_created', ['workspace_id', sa.literal_column('starred DESC'), sa.literal_column('created_ts DESC')], unique=False)

    if 'gateway_schema_context' not in existing_tables:
        op.create_table('gateway_schema_context',
        sa.Column('fingerprint', sa.String(length=64), nullable=False),
        sa.Column('context_json', sa.Text(), nullable=False),
        sa.Column('last_indexed_at', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('fingerprint')
        )
        with op.batch_alter_table('gateway_schema_context', schema=None) as batch_op:
            batch_op.create_index('ix_schema_context_indexed_at', ['last_indexed_at'], unique=False)

    # gateway_lineage_edges / gateway_share_tokens FK-reference
    # gateway_saved_queries.id, so must be created after it (order preserved
    # from autogenerate — it already sequenced dependents correctly).
    if 'gateway_lineage_edges' not in existing_tables:
        op.create_table('gateway_lineage_edges',
        sa.Column('table_name', sa.String(length=255), nullable=False),
        sa.Column('saved_query_id', sa.String(length=64), nullable=False),
        sa.Column('workspace_id', sa.String(length=64), nullable=False),
        sa.Column('updated_at', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['saved_query_id'], ['gateway_saved_queries.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('table_name', 'saved_query_id')
        )
        with op.batch_alter_table('gateway_lineage_edges', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_lineage_edges_workspace_id'), ['workspace_id'], unique=False)

    if 'gateway_share_tokens' not in existing_tables:
        op.create_table('gateway_share_tokens',
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('saved_query_id', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['saved_query_id'], ['gateway_saved_queries.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('token')
        )
        with op.batch_alter_table('gateway_share_tokens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_gateway_share_tokens_saved_query_id'), ['saved_query_id'], unique=False)

    if 'audit_ledger' not in existing_tables:
        op.create_table('audit_ledger',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(length=64), nullable=False),
        sa.Column('subject_id', sa.String(length=128), nullable=False),
        sa.Column('subject_type', sa.String(length=32), nullable=False),
        sa.Column('preparer_id', sa.String(length=128), nullable=False),
        sa.Column('reviewer_id', sa.String(length=128), nullable=True),
        sa.Column('decided_at', sa.String(length=64), nullable=True),
        sa.Column('cert_hash', sa.String(length=128), nullable=False),
        sa.Column('input_fingerprint', sa.String(length=128), nullable=False),
        sa.Column('payload_json', sa.Text(), nullable=False),
        sa.Column('prev_hash', sa.String(length=64), nullable=False),
        sa.Column('record_hash', sa.String(length=64), nullable=False),
        sa.Column('ts', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'seq', name='uq_audit_ledger_tenant_seq')
        )
        with op.batch_alter_table('audit_ledger', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_audit_ledger_tenant_id'), ['tenant_id'], unique=False)
            batch_op.create_index('ix_audit_ledger_tenant_subject', ['tenant_id', 'subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if 'audit_ledger' in existing_tables:
        with op.batch_alter_table('audit_ledger', schema=None) as batch_op:
            batch_op.drop_index('ix_audit_ledger_tenant_subject')
            batch_op.drop_index(batch_op.f('ix_audit_ledger_tenant_id'))
        op.drop_table('audit_ledger')

    if 'gateway_share_tokens' in existing_tables:
        with op.batch_alter_table('gateway_share_tokens', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_gateway_share_tokens_saved_query_id'))
        op.drop_table('gateway_share_tokens')

    if 'gateway_lineage_edges' in existing_tables:
        with op.batch_alter_table('gateway_lineage_edges', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_gateway_lineage_edges_workspace_id'))
        op.drop_table('gateway_lineage_edges')

    if 'gateway_schema_context' in existing_tables:
        with op.batch_alter_table('gateway_schema_context', schema=None) as batch_op:
            batch_op.drop_index('ix_schema_context_indexed_at')
        op.drop_table('gateway_schema_context')

    if 'gateway_saved_queries' in existing_tables:
        with op.batch_alter_table('gateway_saved_queries', schema=None) as batch_op:
            batch_op.drop_index('ix_saved_queries_ws_starred_created')
            batch_op.drop_index(batch_op.f('ix_gateway_saved_queries_workspace_id'))
        op.drop_table('gateway_saved_queries')

    if 'gateway_query_history' in existing_tables:
        with op.batch_alter_table('gateway_query_history', schema=None) as batch_op:
            batch_op.drop_index('ix_query_history_created_ts_desc')
            batch_op.drop_index(batch_op.f('ix_gateway_query_history_created_ts'))
        op.drop_table('gateway_query_history')

    if 'gateway_pipelines' in existing_tables:
        with op.batch_alter_table('gateway_pipelines', schema=None) as batch_op:
            batch_op.drop_index('ix_pipelines_ws_created')
            batch_op.drop_index(batch_op.f('ix_gateway_pipelines_workspace_id'))
        op.drop_table('gateway_pipelines')

    if 'gateway_file_metadata' in existing_tables:
        with op.batch_alter_table('gateway_file_metadata', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_gateway_file_metadata_mtime'))
        op.drop_table('gateway_file_metadata')

    if 'gateway_chat_messages' in existing_tables:
        with op.batch_alter_table('gateway_chat_messages', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_gateway_chat_messages_workspace_id'))
            batch_op.drop_index('ix_chat_ws_session_created')
        op.drop_table('gateway_chat_messages')
    # ### end Alembic commands ###
