import { describe, expect, it } from 'vitest';

import { verifyInclusion, type InclusionProof } from '../merkle';
import vectors from './merkleVectors.json';

// Generated by the backend's OWN shared.merkle (build_tree_root / inclusion_proof)
// over every index of trees of sizes 1..17, so this proves the browser verifier
// agrees with the implementation that produced the roots — not just with itself.
type Vector = { tree_size: number; record_hashes: string[]; root: string; proofs: string[][] };
const VECTORS = vectors as Vector[];

const proofFor = (v: Vector, i: number): InclusionProof => ({
  record_hash: v.record_hashes[i],
  leaf_index: i,
  tree_size: v.tree_size,
  proof_hex: v.proofs[i],
  root_hash_hex: v.root,
});

const flip = (hex: string) => (hex[0] === '0' ? '1' : '0') + hex.slice(1);

describe('verifyInclusion — agrees with the backend on every generated proof', () => {
  it('has real coverage (odd sizes, powers of two, single leaf)', () => {
    const sizes = VECTORS.map((v) => v.tree_size);
    expect(sizes).toEqual(expect.arrayContaining([1, 2, 3, 5, 7, 8, 9, 13, 17]));
    expect(VECTORS.reduce((n, v) => n + v.tree_size, 0)).toBeGreaterThan(100);
  });

  it.each(VECTORS.map((v) => [v.tree_size, v] as const))('accepts every leaf of a %i-leaf tree', async (_n, v) => {
    for (let i = 0; i < v.tree_size; i++) {
      expect(await verifyInclusion(proofFor(v, i)), `leaf ${i}/${v.tree_size}`).toBe(true);
    }
  });
});

describe('verifyInclusion — rejects every kind of tampering', () => {
  const v = VECTORS.find((x) => x.tree_size === 13)!; // odd size: exercises promoted nodes

  it('rejects a different record hash at the same position', async () => {
    expect(await verifyInclusion({ ...proofFor(v, 4), record_hash: v.record_hashes[5] })).toBe(false);
  });

  it('rejects the right proof claimed at the wrong leaf index', async () => {
    expect(await verifyInclusion({ ...proofFor(v, 4), leaf_index: 5 })).toBe(false);
  });

  it('rejects a tree size whose path SHAPE differs, and matches the backend where it does not', async () => {
    // RFC 6962 inclusion proofs bind (root, leaf, index); tree_size only fixes
    // the shape of the path. For leaf 4 the shape is identical for sizes 12..16
    // (the backend's own verify_inclusion returns True for all of them, checked
    // when this test was written) and differs at 17. So a proof does NOT prove
    // the tree size, and the UI must not present it as proven.
    for (const size of [12, 14, 15, 16]) {
      expect(await verifyInclusion({ ...proofFor(v, 4), tree_size: size }), `size ${size}`).toBe(true);
    }
    expect(await verifyInclusion({ ...proofFor(v, 4), tree_size: 17 })).toBe(false);
    expect(await verifyInclusion({ ...proofFor(v, 4), tree_size: 4 })).toBe(false);
  });

  it('rejects a wrong root', async () => {
    expect(await verifyInclusion({ ...proofFor(v, 4), root_hash_hex: flip(v.root) })).toBe(false);
  });

  it('rejects a corrupted sibling anywhere in the path', async () => {
    const p = proofFor(v, 4);
    for (let k = 0; k < p.proof_hex.length; k++) {
      const proof_hex = p.proof_hex.map((h, j) => (j === k ? flip(h) : h));
      expect(await verifyInclusion({ ...p, proof_hex }), `sibling ${k}`).toBe(false);
    }
  });

  it('rejects a proof that is too short or too long', async () => {
    const p = proofFor(v, 4);
    expect(await verifyInclusion({ ...p, proof_hex: p.proof_hex.slice(0, -1) })).toBe(false);
    expect(await verifyInclusion({ ...p, proof_hex: [...p.proof_hex, p.proof_hex[0]] })).toBe(false);
  });

  it('rejects a non-empty proof for a single-leaf tree', async () => {
    const one = VECTORS.find((x) => x.tree_size === 1)!;
    expect(await verifyInclusion(proofFor(one, 0))).toBe(true);
    expect(await verifyInclusion({ ...proofFor(one, 0), proof_hex: [one.root] })).toBe(false);
  });

  it('treats the leaf as the UTF-8 hex STRING, not the raw digest (the easy port bug)', async () => {
    // If a port hashed the decoded 32 raw bytes instead, real proofs would fail;
    // conversely a proof built that way must not verify against the real root.
    const p = proofFor(v, 4);
    expect(await verifyInclusion({ ...p, record_hash: p.record_hash.toUpperCase() })).toBe(false);
  });
});

describe('verifyInclusion — malformed input is false, never a throw', () => {
  const v = VECTORS.find((x) => x.tree_size === 5)!;
  const good = proofFor(v, 2);

  it.each([
    ['negative index', { leaf_index: -1 }],
    ['index >= size', { leaf_index: 5 }],
    ['non-integer index', { leaf_index: 1.5 }],
    ['zero size', { tree_size: 0 }],
    ['non-hex root', { root_hash_hex: 'zz'.repeat(32) }],
    ['short root', { root_hash_hex: 'ab'.repeat(16) }],
    ['odd-length root', { root_hash_hex: 'a'.repeat(63) }],
    ['non-hex sibling', { proof_hex: ['nothex', ...good.proof_hex.slice(1)] }],
    ['short sibling', { proof_hex: ['ab', ...good.proof_hex.slice(1)] }],
    ['empty record hash', { record_hash: '' }],
  ])('%s', async (_name, patch) => {
    await expect(verifyInclusion({ ...good, ...patch } as InclusionProof)).resolves.toBe(false);
  });

  it('does not throw when proof_hex is not an array', async () => {
    await expect(verifyInclusion({ ...good, proof_hex: null as unknown as string[] })).resolves.toBe(false);
  });
});
