"""
Public surface of the auto-generated SDK package ``aura_gateway_client``.

Re-exports every Pydantic model from ``models`` plus the typed
``Client`` + exception classes from ``client``. Regenerate via
``scripts/generate_sdk.py`` — see that module for the CLI; never
edit this file by hand.
"""
from __future__ import annotations

from .client import (
    APIError,
    Client,
    NotFoundError,
    RetryPolicy,
    ServiceUnavailableError,
    UnauthorizedError,
)
from .models import (
    AgentAsyncResponse,
    AgentExecuteRequest,
    AgentExecuteResponse,
    AgentPlanResponse,
    Body_analyze_results_api_v1_analyze_results_post,
    Body_upload_universal_api_v1_upload_post,
    ChatRequest,
    ConnectionCreateRequest,
    ConnectorTableListResponse,
    CreateStreamPipelineRequest,
    ETLNaturalLanguageRequest,
    ETLPipelineRequest,
    ETLTransformStep,
    ExecuteQueryRequest,
    ExecuteQueryResponse,
    FeedbackRequest,
    HTTPValidationError,
    HookCreateRequest,
    HookUpdateRequest,
    LateDataPolicy,
    PatternSearchRequest,
    PipelineExecuteRequest,
    PipelineGenerateRequest,
    PipelineSaveRequest,
    ProfileTableRequest,
    ProposalUpdateRequest,
    QueryRequest,
    SemanticFieldPayload,
    SemanticModelPayload,
    StreamSink,
    StreamSinkType,
    StreamSource,
    StreamSourceType,
    StreamTransform,
    TokenRequest,
    TokenResponse,
    TransformType,
    UpdateStreamPipelineRequest,
    UserInfo,
    ValidateQueryRequest,
    ValidateQueryResponse,
    ValidationError,
    WebhookCreateRequest,
    WebhookUpdateRequest,
    WindowConfig,
    WindowType,
    _ChatExecuteRequest,
)

__all__ = [
    "APIError",
    "Client",
    "NotFoundError",
    "RetryPolicy",
    "ServiceUnavailableError",
    "UnauthorizedError",
    "AgentAsyncResponse",
    "AgentExecuteRequest",
    "AgentExecuteResponse",
    "AgentPlanResponse",
    "Body_analyze_results_api_v1_analyze_results_post",
    "Body_upload_universal_api_v1_upload_post",
    "ChatRequest",
    "ConnectionCreateRequest",
    "ConnectorTableListResponse",
    "CreateStreamPipelineRequest",
    "ETLNaturalLanguageRequest",
    "ETLPipelineRequest",
    "ETLTransformStep",
    "ExecuteQueryRequest",
    "ExecuteQueryResponse",
    "FeedbackRequest",
    "HTTPValidationError",
    "HookCreateRequest",
    "HookUpdateRequest",
    "LateDataPolicy",
    "PatternSearchRequest",
    "PipelineExecuteRequest",
    "PipelineGenerateRequest",
    "PipelineSaveRequest",
    "ProfileTableRequest",
    "ProposalUpdateRequest",
    "QueryRequest",
    "SemanticFieldPayload",
    "SemanticModelPayload",
    "StreamSink",
    "StreamSinkType",
    "StreamSource",
    "StreamSourceType",
    "StreamTransform",
    "TokenRequest",
    "TokenResponse",
    "TransformType",
    "UpdateStreamPipelineRequest",
    "UserInfo",
    "ValidateQueryRequest",
    "ValidateQueryResponse",
    "ValidationError",
    "WebhookCreateRequest",
    "WebhookUpdateRequest",
    "WindowConfig",
    "WindowType",
    "_ChatExecuteRequest",
]
