/* Browser-side RFC 6962 Merkle inclusion verification (BUG-159).

   A direct port of aurabackend/shared/merkle.py's verify_inclusion. It exists so
   an auditor's browser can RECOMPUTE the root from a record hash, its leaf index
   and the proof path instead of trusting a "verified" flag from the server.

   Two details that are easy to get wrong, both mirroring the backend exactly:
     - the leaf is the UTF-8 bytes of the hex record_hash STRING (not the raw
       32-byte digest): shared/audit_ledger.py does leaf_hash(record_hash.encode());
     - leaf hash = SHA-256(0x00 || data), node hash = SHA-256(0x01 || left || right),
       so a leaf can never collide with an internal node.
   Tested against vectors generated by the backend's own implementation. */

export interface InclusionProof {
  /** The ledger record_hash the proof is for (hex). */
  record_hash: string;
  leaf_index: number;
  tree_size: number;
  /** Sibling hashes ordered leaf -> root (hex). */
  proof_hex: string[];
  root_hash_hex: string;
}

const encoder = new TextEncoder();

function subtle(): SubtleCrypto {
  const s = globalThis.crypto?.subtle;
  if (!s) {
    // crypto.subtle only exists in secure contexts (https or localhost).
    throw new Error('This browser context cannot hash (WebCrypto needs HTTPS or localhost).');
  }
  return s;
}

function hexToBytes(hex: unknown): Uint8Array | null {
  if (typeof hex !== 'string' || hex.length % 2 !== 0 || !/^[0-9a-f]*$/i.test(hex)) return null;
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

async function sha256(prefix: number, ...parts: Uint8Array[]): Promise<Uint8Array> {
  const total = 1 + parts.reduce((n, p) => n + p.length, 0);
  const buf = new Uint8Array(total);
  buf[0] = prefix;
  let off = 1;
  for (const p of parts) { buf.set(p, off); off += p.length; }
  return new Uint8Array(await subtle().digest('SHA-256', buf));
}

const leafHash = (data: Uint8Array) => sha256(0x00, data);
const nodeHash = (left: Uint8Array, right: Uint8Array) => sha256(0x01, left, right);

function equal(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

/** True iff the proof reconstructs `root_hash_hex` from `record_hash` at
    `leaf_index` in a tree of `tree_size`. Malformed input is `false`, never a throw. */
export async function verifyInclusion(p: InclusionProof): Promise<boolean> {
  const { leaf_index: index, tree_size: size } = p;
  if (!Number.isInteger(index) || !Number.isInteger(size) || index < 0 || index >= size) return false;
  if (typeof p.record_hash !== 'string' || p.record_hash === '' || !Array.isArray(p.proof_hex)) return false;

  const root = hexToBytes(p.root_hash_hex);
  const proof = p.proof_hex.map(hexToBytes);
  if (!root || root.length !== 32 || proof.some((x) => x === null || x.length !== 32)) return false;
  const siblings = proof as Uint8Array[];

  const leaf = await leafHash(encoder.encode(p.record_hash));
  if (size === 1) return siblings.length === 0 && equal(leaf, root);

  let computed = leaf;
  let fn = index;
  let ln = size - 1;
  let used = 0;
  while (ln > 0) {
    if (fn % 2 === 1 || fn === ln) {
      // A right child pairs with its left sibling; the right-most node of an
      // odd-sized level is promoted unchanged (RFC 6962 does not duplicate it).
      if (fn % 2 === 1) {
        if (used >= siblings.length) return false;
        computed = await nodeHash(siblings[used++], computed);
      }
    } else {
      if (used >= siblings.length) return false;
      computed = await nodeHash(computed, siblings[used++]);
    }
    fn = Math.floor(fn / 2);
    ln = Math.floor(ln / 2);
  }
  // Leftover proof elements mean the proof is longer than the tree allows.
  if (used !== siblings.length) return false;
  return equal(computed, root);
}
