"""
Evolution Engine — Data Models
================================
ORM and Pydantic models for tracking execution patterns,
learned improvements, and self-evolution history.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from sqlalchemy import JSON, Boolean, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from metadata_store.db import Base


class ImprovementStatus(str, Enum):
    PROPOSED = "proposed"
    TESTING = "testing"
    VALIDATED = "validated"
    DEPLOYED = "deployed"
    REJECTED = "rejected"


class PatternType(str, Enum):
    PIPELINE_STRUCTURE = "pipeline_structure"
    QUERY_OPTIMIZATION = "query_optimization"
    SCHEMA_DESIGN = "schema_design"
    DATA_QUALITY = "data_quality"
    RECOVERY_SHIM = "recovery_shim"
    AGENT_PLAN = "agent_plan"


# ── ORM Tables ──────────────────────────────────────────────────────

class ExecutionPattern(Base):
    """Records successful execution patterns for future reuse."""
    __tablename__ = "evolution_execution_patterns"

    id: Mapped[str] = mapped_column(String(64), primary_key=True,
                                     default=lambda: uuid.uuid4().hex[:16])
    pattern_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    intent_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    intent_summary: Mapped[str] = mapped_column(Text, nullable=False)
    pattern_data: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    success_count: Mapped[int] = mapped_column(Integer, default=1)
    failure_count: Mapped[int] = mapped_column(Integer, default=0)
    avg_duration_ms: Mapped[float] = mapped_column(Float, default=0.0)
    last_used_at: Mapped[datetime] = mapped_column(DateTime,
                                                    default=lambda: datetime.now(timezone.utc))
    created_at: Mapped[datetime] = mapped_column(DateTime,
                                                  default=lambda: datetime.now(timezone.utc))


class ImprovementProposal(Base):
    """A proposed system improvement generated by the evolution engine."""
    __tablename__ = "evolution_improvement_proposals"

    id: Mapped[str] = mapped_column(String(64), primary_key=True,
                                     default=lambda: uuid.uuid4().hex[:16])
    target: Mapped[str] = mapped_column(String(128), nullable=False)  # e.g. "PipelineAgent"
    improvement_type: Mapped[str] = mapped_column(String(64), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=True)
    proposed_change: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    status: Mapped[str] = mapped_column(String(32),
                                         default=ImprovementStatus.PROPOSED.value, index=True)
    confidence_score: Mapped[float] = mapped_column(Float, default=0.0)
    test_results: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime,
                                                  default=lambda: datetime.now(timezone.utc))
    deployed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)


class SystemEvolutionLog(Base):
    """Audit trail of all self-improvement cycles."""
    __tablename__ = "evolution_system_log"

    id: Mapped[str] = mapped_column(String(64), primary_key=True,
                                     default=lambda: uuid.uuid4().hex[:16])
    cycle_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    event_type: Mapped[str] = mapped_column(String(64), nullable=False)
    component: Mapped[str] = mapped_column(String(128), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    outcome: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime,
                                                  default=lambda: datetime.now(timezone.utc))


class AgentFeedback(Base):
    """Explicit and implicit feedback on agent executions."""
    __tablename__ = "evolution_agent_feedback"

    id: Mapped[str] = mapped_column(String(64), primary_key=True,
                                     default=lambda: uuid.uuid4().hex[:16])
    session_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    agent_name: Mapped[str] = mapped_column(String(128), nullable=False)
    task_type: Mapped[str] = mapped_column(String(64), nullable=False)
    user_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    agent_output: Mapped[Dict[str, Any]] = mapped_column(JSON, default=dict)
    success: Mapped[bool] = mapped_column(Boolean, default=True)
    duration_ms: Mapped[float] = mapped_column(Float, default=0.0)
    user_rating: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)  # 1-5
    correction: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # user correction
    created_at: Mapped[datetime] = mapped_column(DateTime,
                                                  default=lambda: datetime.now(timezone.utc))
