"""
Auto-generated typed Client — DO NOT EDIT BY HAND.

Regenerate with:

    python scripts/generate_sdk.py \
        --openapi aurabackend/openapi.json \
        --output sdk_clients/aura_orchestration_client \
        --package-name aura_orchestration_client

Source schema fingerprint: 63415a368d3e4f8b
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Literal, Optional, Tuple, Union

import httpx


# ── Exceptions ────────────────────────────────────────────────────────

class APIError(RuntimeError):
    """Base class for any HTTP-level error from the service."""

    def __init__(
        self, message: str, *,
        status_code: Optional[int] = None,
        body: Optional[str] = None,
    ) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.body = body


class NotFoundError(APIError):
    """404 — resource not found."""


class UnauthorizedError(APIError):
    """401 / 403 — auth required or denied."""


class ServiceUnavailableError(APIError):
    """503 — service degraded; caller may retry after backoff."""


# ── Retry policy ──────────────────────────────────────────────────────

@dataclass
class RetryPolicy:
    """Bounded retry for idempotent GETs only.

    Three attempts over ~3 seconds with exponential backoff.
    Retries fire on transient 429 / 503 responses; never on 4xx
    semantics or network errors that the caller should see.
    """
    max_attempts: int = 3
    initial_delay_s: float = 0.3
    backoff_factor: float = 2.0
    retryable_statuses: Tuple[int, ...] = (429, 503)


# ── Client ────────────────────────────────────────────────────────────

class Client:
    """Auto-generated typed HTTP client for ``aura_orchestration_client``.

    Method-per-operation surface — every public method corresponds to
    one OpenAPI path × HTTP-method pair. Path parameters are
    positional; request body and query parameters are keyword. Methods
    return either a typed Pydantic model (when the OpenAPI 200 response
    references a component schema) or a plain ``Dict[str, Any]`` for
    untyped responses.

    See README.md for the regeneration command. Do not edit this file
    by hand — changes will be overwritten on next regeneration.
    """

    def __init__(
        self,
        base_url: str = "http://localhost:8000",
        *,
        prefix: str = "",
        api_key: Optional[str] = None,
        timeout: Union[float, httpx.Timeout] = 30.0,
        retry: Optional[RetryPolicy] = None,
        client: Optional[httpx.Client] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._prefix = prefix.rstrip("/") if prefix else ""
        self._retry = retry or RetryPolicy()
        headers = {"Accept": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        self._owns_client = client is None
        self._http = client or httpx.Client(timeout=timeout, headers=headers)
        if not self._owns_client:
            for k, v in headers.items():
                self._http.headers.setdefault(k, v)

    def __enter__(self) -> "Client":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        if self._owns_client:
            self._http.close()

    def _url(self, path: str) -> str:
        return f"{self._base_url}{self._prefix}{path}"

    def _request(
        self, method: str, path: str, *,
        params: Optional[Dict[str, Any]] = None,
        json: Any = None,
    ) -> Any:
        """Dispatch one HTTP request and translate errors.

        Idempotent GET requests retry on transient (429/503) status
        codes per ``self._retry``. POST/PUT/DELETE/PATCH never retry —
        the caller may have produced visible side effects already.
        """
        import time
        attempts = self._retry.max_attempts if method == "GET" else 1
        delay = self._retry.initial_delay_s
        last_resp: Optional[httpx.Response] = None
        for attempt in range(attempts):
            resp = self._http.request(
                method, self._url(path), params=params, json=json,
            )
            if (
                method == "GET"
                and resp.status_code in self._retry.retryable_statuses
                and attempt < attempts - 1
            ):
                last_resp = resp
                time.sleep(delay)
                delay *= self._retry.backoff_factor
                continue
            return self._handle_response(resp)
        # All retries exhausted.
        assert last_resp is not None
        return self._handle_response(last_resp)

    @staticmethod
    def _handle_response(resp: httpx.Response) -> Any:
        """Translate HTTP status to typed exception or return JSON."""
        if resp.status_code == 404:
            raise NotFoundError(
                f"not found: {resp.url}",
                status_code=404, body=resp.text,
            )
        if resp.status_code in (401, 403):
            raise UnauthorizedError(
                f"unauthorized: {resp.url}",
                status_code=resp.status_code, body=resp.text,
            )
        if resp.status_code == 503:
            raise ServiceUnavailableError(
                f"service unavailable: {resp.url}",
                status_code=503, body=resp.text,
            )
        if resp.status_code >= 400:
            raise APIError(
                f"HTTP {resp.status_code} on {resp.url}",
                status_code=resp.status_code, body=resp.text,
            )
        # 2xx — may have empty body for 204 No Content.
        if resp.status_code == 204 or not resp.content:
            return {}
        return resp.json()

    # ── Operation methods (one per OpenAPI path × method) ─────────────

    def _handshake_endpoint_mcp_handshake(self, body: "MCPHandshakeRequest") -> "MCPHandshakeResponse":
        """Handshake Endpoint"""
        url = "/mcp/handshake"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = self._request("POST", url, params=params, json=json_body)
        from .models import MCPHandshakeResponse
        return MCPHandshakeResponse.model_validate(response)

    def _invoke_endpoint_mcp_invoke(self, body: "ToolInvocation") -> "ToolInvocationResult":
        """Invoke Endpoint"""
        url = "/mcp/invoke"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = self._request("POST", url, params=params, json=json_body)
        from .models import ToolInvocationResult
        return ToolInvocationResult.model_validate(response)

    def generate_query_v1_orchestrations_query(self, body: "ChatRequest") -> "AgentResponse":
        """Generate Query"""
        url = "/v1/orchestrations/query"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = self._request("POST", url, params=params, json=json_body)
        from .models import AgentResponse
        return AgentResponse.model_validate(response)

    def health(self) -> Dict[str, Any]:
        """Health"""
        url = "/health"
        params = None
        json_body = None
        response = self._request("GET", url, params=params, json=json_body)
        return response

    def root_(self) -> Dict[str, Any]:
        """Root"""
        url = "/"
        params = None
        json_body = None
        response = self._request("GET", url, params=params, json=json_body)
        return response

# ── AsyncClient — async mirror of Client ──────────────────────────────

class AsyncClient:
    """Auto-generated async HTTP client for ``aura_orchestration_client``.

    Mirror of ``Client`` with full asyncio support. Same operation
    surface, same argument conventions, same retry policy + typed
    exception hierarchy — every method is an ``async def`` that
    awaits a single httpx request. Use ``async with`` for context-
    managed lifecycle. Suitable for FastAPI route handlers and
    async-notebook environments.
    """

    def __init__(
        self,
        base_url: str = "http://localhost:8000",
        *,
        prefix: str = "",
        api_key: Optional[str] = None,
        timeout: Union[float, httpx.Timeout] = 30.0,
        retry: Optional[RetryPolicy] = None,
        client: Optional[httpx.AsyncClient] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._prefix = prefix.rstrip("/") if prefix else ""
        self._retry = retry or RetryPolicy()
        headers = {"Accept": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        self._owns_client = client is None
        self._http = client or httpx.AsyncClient(timeout=timeout, headers=headers)
        if not self._owns_client:
            for k, v in headers.items():
                self._http.headers.setdefault(k, v)

    async def __aenter__(self) -> "AsyncClient":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        if self._owns_client:
            await self._http.aclose()

    def _url(self, path: str) -> str:
        return f"{self._base_url}{self._prefix}{path}"

    async def _request(
        self, method: str, path: str, *,
        params: Optional[Dict[str, Any]] = None,
        json: Any = None,
    ) -> Any:
        """Async dispatch with the same retry contract as Client._request.

        Idempotent GETs retry on transient (429/503) status codes
        using ``asyncio.sleep`` between attempts. POSTs/PUTs/DELETEs
        never retry — the caller may have produced visible side
        effects already.
        """
        import asyncio
        attempts = self._retry.max_attempts if method == "GET" else 1
        delay = self._retry.initial_delay_s
        last_resp: Optional[httpx.Response] = None
        for attempt in range(attempts):
            resp = await self._http.request(
                method, self._url(path), params=params, json=json,
            )
            if (
                method == "GET"
                and resp.status_code in self._retry.retryable_statuses
                and attempt < attempts - 1
            ):
                last_resp = resp
                await asyncio.sleep(delay)
                delay *= self._retry.backoff_factor
                continue
            return Client._handle_response(resp)
        assert last_resp is not None
        return Client._handle_response(last_resp)

    # ── Operation methods (async mirrors of Client) ──────────────────

    async def _handshake_endpoint_mcp_handshake(self, body: "MCPHandshakeRequest") -> "MCPHandshakeResponse":
        """Handshake Endpoint"""
        url = "/mcp/handshake"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = await self._request("POST", url, params=params, json=json_body)
        from .models import MCPHandshakeResponse
        return MCPHandshakeResponse.model_validate(response)

    async def _invoke_endpoint_mcp_invoke(self, body: "ToolInvocation") -> "ToolInvocationResult":
        """Invoke Endpoint"""
        url = "/mcp/invoke"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = await self._request("POST", url, params=params, json=json_body)
        from .models import ToolInvocationResult
        return ToolInvocationResult.model_validate(response)

    async def generate_query_v1_orchestrations_query(self, body: "ChatRequest") -> "AgentResponse":
        """Generate Query"""
        url = "/v1/orchestrations/query"
        params = None
        json_body = body.model_dump(mode='json') if hasattr(body, 'model_dump') else body
        response = await self._request("POST", url, params=params, json=json_body)
        from .models import AgentResponse
        return AgentResponse.model_validate(response)

    async def health(self) -> Dict[str, Any]:
        """Health"""
        url = "/health"
        params = None
        json_body = None
        response = await self._request("GET", url, params=params, json=json_body)
        return response

    async def root_(self) -> Dict[str, Any]:
        """Root"""
        url = "/"
        params = None
        json_body = None
        response = await self._request("GET", url, params=params, json=json_body)
        return response
