"""
Pipeline Data Models
====================
Typed definitions for the complete pipeline: Source → Process → Sink.

Every pipeline is a JSON-serialisable object that can be:
  1. Generated by AI from a natural language prompt
  2. Built interactively in the frontend
  3. Stored, versioned, and re-executed
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ────────────────────────────────────────────────────────────────────
# Enums
# ────────────────────────────────────────────────────────────────────

class SourceType(str, Enum):
    """Where data comes from"""
    FILE = "file"               # uploaded CSV, Parquet, JSON
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    BIGQUERY = "bigquery"
    DUCKDB = "duckdb"           # existing DuckDB table / view


class SinkType(str, Enum):
    """Where data goes"""
    FILE = "file"               # CSV, Parquet, JSON download
    POSTGRESQL = "postgresql"   # write to PG table
    DUCKDB = "duckdb"           # persist in DuckDB table
    PREVIEW = "preview"         # no write, return rows only


class StepType(str, Enum):
    """Processing operations"""
    FILTER = "filter"
    SORT = "sort"
    DROP_COLUMNS = "drop_columns"
    RENAME_COLUMNS = "rename_columns"
    ADD_COLUMN = "add_column"
    CAST_TYPE = "cast_type"
    FILL_MISSING = "fill_missing"
    DEDUPLICATE = "deduplicate"
    AGGREGATE = "aggregate"
    JOIN = "join"
    WINDOW = "window"
    PIVOT = "pivot"
    UNPIVOT = "unpivot"
    LIMIT = "limit"
    UNION = "union"
    CUSTOM_SQL = "custom_sql"


class PipelineStatus(str, Enum):
    DRAFT = "draft"
    READY = "ready"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"


# ────────────────────────────────────────────────────────────────────
# Source
# ────────────────────────────────────────────────────────────────────

class PipelineSource(BaseModel):
    """Defines where data is read from."""
    type: SourceType
    # For FILE sources
    file_name: Optional[str] = None
    # For database sources
    connection: Optional[Dict[str, Any]] = None
    table: Optional[str] = None
    query: Optional[str] = None         # custom SELECT instead of full table

    def label(self) -> str:
        if self.type == SourceType.FILE:
            return self.file_name or "unknown_file"
        return f"{self.type.value}://{self.table or 'query'}"


class JoinSource(BaseModel):
    """Secondary source for JOIN steps."""
    type: SourceType
    file_name: Optional[str] = None
    connection: Optional[Dict[str, Any]] = None
    table: Optional[str] = None
    query: Optional[str] = None


# ────────────────────────────────────────────────────────────────────
# Processing Step
# ────────────────────────────────────────────────────────────────────

class ProcessingStep(BaseModel):
    """One transformation operation in the pipeline."""
    id: str = Field(default_factory=lambda: f"step_{uuid.uuid4().hex[:6]}")
    type: StepType
    description: str = ""
    config: Dict[str, Any] = Field(default_factory=dict)
    # For JOIN steps: the right-hand source
    join_source: Optional[JoinSource] = None


# ────────────────────────────────────────────────────────────────────
# Sink
# ────────────────────────────────────────────────────────────────────

class PipelineSink(BaseModel):
    """Defines where processed data is written."""
    type: SinkType
    # For FILE sinks
    format: Optional[str] = "csv"       # csv, parquet, json
    file_name: Optional[str] = None
    # For database sinks
    connection: Optional[Dict[str, Any]] = None
    table: Optional[str] = None
    if_exists: str = "replace"          # replace, append, fail


# ────────────────────────────────────────────────────────────────────
# Pipeline Definition
# ────────────────────────────────────────────────────────────────────

class Pipeline(BaseModel):
    """Complete pipeline: Source → Process → Sink."""
    id: str = Field(default_factory=lambda: f"pipe_{uuid.uuid4().hex[:8]}")
    name: str
    description: str = ""
    source: PipelineSource
    steps: List[ProcessingStep] = Field(default_factory=list)
    sink: PipelineSink
    # Metadata
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: Optional[str] = None
    status: PipelineStatus = PipelineStatus.DRAFT
    # Scheduling (optional)
    schedule: Optional[str] = None      # cron expression
    # AI generation metadata
    generated_from_prompt: Optional[str] = None
    tags: List[str] = Field(default_factory=list)


# ────────────────────────────────────────────────────────────────────
# Pipeline Run (execution record)
# ────────────────────────────────────────────────────────────────────

class PipelineRun(BaseModel):
    """Record of a single pipeline execution."""
    run_id: str = Field(default_factory=lambda: f"run_{uuid.uuid4().hex[:8]}")
    pipeline_id: str
    status: PipelineStatus = PipelineStatus.RUNNING
    started_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    finished_at: Optional[str] = None
    # Results
    rows_read: int = 0
    rows_written: int = 0
    columns_in: List[str] = Field(default_factory=list)
    columns_out: List[str] = Field(default_factory=list)
    output_file: Optional[str] = None
    output_table: Optional[str] = None
    # Generated SQL (for transparency)
    sql_generated: Optional[str] = None
    steps_executed: int = 0
    steps_skipped: int = 0
    preview_data: Optional[List[Dict[str, Any]]] = None
    error: Optional[str] = None
    duration_ms: float = 0.0
